# Generated by Django 4.1.5 on 2023-04-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('unternehmen', models.CharField(max_length=100)),
                ('nachricht', models.TextField()),
            ],
        ),
    ]
