# Generated by Django 4.1.5 on 2023-04-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donateapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donate',
            old_name='reason',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='donate',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
